from scrapy.item import Item
from scrapy.item import Field

class PerGame(Item):
	pid = Field()
	name = Field()
	season = Field()
	age = Field()
	team = Field()
	league = Field()
	position = Field()
	games = Field()
	games_started = Field()
	minutes_per_game = Field()
	fg_per_game = Field()
	fga_per_game = Field()
	fg_pct = Field()
	fg3_per_game = Field()
	fg3a_per_game = Field()
	fg3_pct = Field()
	fg2_per_game = Field()
	fg2a_per_game = Field()
	fg2_pct = Field()
	efg_pct = Field()
	ft_per_game = Field()
	fta_per_game = Field()
	ft_pct = Field()
	orb_per_game = Field()
	drb_per_game = Field()
	trb_per_game = Field()
	ast_per_game = Field()
	stl_per_game = Field()
	blk_per_game = Field()
	tov_per_game = Field()
	pf_per_game = Field()
	pts_per_game = Field()



class Totals(Item):
	pid = Field()
	name = Field()
	season = Field()
	age = Field()
	team = Field()
	league = Field()
	position = Field()
	games = Field()
	games_started = Field()
	minutes = Field()
	fg = Field()
	fga = Field()
	fg_pct = Field()
	fg3 = Field()
	fg3a = Field()
	fg3_pct = Field()
	fg2 = Field()
	fg2a = Field()
	fg2_pct = Field()
	efg_pct = Field()
	ft = Field()
	fta = Field()
	ft_pct = Field()
	orb = Field()
	drb = Field()
	trb = Field()
	ast = Field()
	stl = Field()
	blk = Field()
	tov = Field()
	pf = Field()
	pts = Field()

class PerPos(Item):
	pid = Field()
	name = Field()
	season = Field()
	age = Field()
	team = Field()
	league = Field()
	position = Field()
	games = Field()
	games_started = Field()
	minutes_per_pos = Field()
	fg_per_pos = Field()
	fga_per_pos = Field()
	fg_pct = Field()
	fg3_per_pos = Field()
	fg3a_per_pos = Field()
	fg3_pct = Field()
	fg2_per_pos = Field()
	fg2a_per_pos = Field()
	fg2_pct = Field()
	ft_per_pos = Field()
	fta_per_pos = Field()
	ft_pct = Field()
	orb_per_pos = Field()
	drb_per_pos = Field()
	trb_per_pos = Field()
	ast_per_pos = Field()
	stl_per_pos = Field()
	blk_per_pos = Field()
	tov_per_pos = Field()
	pf_per_pos = Field()
	pts_per_pos = Field()
	off_rtg = Field()
	def_rtg = Field()
